[2022-11-28T16:31:12.498+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_try_oop.loadYtApiOperator scheduled__2022-11-28T04:00:00+00:00 [queued]>
[2022-11-28T16:31:12.696+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_try_oop.loadYtApiOperator scheduled__2022-11-28T04:00:00+00:00 [queued]>
[2022-11-28T16:31:12.697+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-28T16:31:12.711+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-11-28T16:31:12.719+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-28T16:31:13.053+0000] {taskinstance.py:1383} INFO - Executing <Task(loadYtApiOperator): loadYtApiOperator> on 2022-11-28 04:00:00+00:00
[2022-11-28T16:31:13.152+0000] {standard_task_runner.py:55} INFO - Started process 736 to run task
[2022-11-28T16:31:13.237+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_try_oop', 'loadYtApiOperator', 'scheduled__2022-11-28T04:00:00+00:00', '--job-id', '845', '--raw', '--subdir', 'DAGS_FOLDER/dag_try_oop.py', '--cfg-path', '/tmp/tmpqkk4niy4']
[2022-11-28T16:31:13.278+0000] {standard_task_runner.py:83} INFO - Job 845: Subtask loadYtApiOperator
[2022-11-28T16:31:14.760+0000] {task_command.py:376} INFO - Running <TaskInstance: dag_try_oop.loadYtApiOperator scheduled__2022-11-28T04:00:00+00:00 [running]> on host 1dd759b3e30c
[2022-11-28T16:31:16.654+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_try_oop
AIRFLOW_CTX_TASK_ID=loadYtApiOperator
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T04:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-28T04:00:00+00:00
[2022-11-28T16:31:17.883+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=dag_try_oop, task_id=loadYtApiOperator, execution_date=20221128T040000, start_date=20221128T163112, end_date=20221128T163117
[2022-11-28T16:31:18.601+0000] {local_task_job.py:159} INFO - Task exited with return code 0
[2022-11-28T16:31:19.216+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-11-29T06:31:54.231+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_try_oop.loadYtApiOperator scheduled__2022-11-28T04:00:00+00:00 [queued]>
[2022-11-29T06:31:54.341+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_try_oop.loadYtApiOperator scheduled__2022-11-28T04:00:00+00:00 [queued]>
[2022-11-29T06:31:54.348+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T06:31:54.355+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-11-29T06:31:54.357+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-29T06:31:54.481+0000] {taskinstance.py:1383} INFO - Executing <Task(loadYtApiOperator): loadYtApiOperator> on 2022-11-28 04:00:00+00:00
[2022-11-29T06:31:54.523+0000] {standard_task_runner.py:55} INFO - Started process 173 to run task
[2022-11-29T06:31:54.545+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_try_oop', 'loadYtApiOperator', 'scheduled__2022-11-28T04:00:00+00:00', '--job-id', '1089', '--raw', '--subdir', 'DAGS_FOLDER/dag_try_oop.py', '--cfg-path', '/tmp/tmpdwb_faay']
[2022-11-29T06:31:54.561+0000] {standard_task_runner.py:83} INFO - Job 1089: Subtask loadYtApiOperator
[2022-11-29T06:31:55.061+0000] {task_command.py:376} INFO - Running <TaskInstance: dag_try_oop.loadYtApiOperator scheduled__2022-11-28T04:00:00+00:00 [running]> on host 92b536e5af67
[2022-11-29T06:31:55.421+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_try_oop
AIRFLOW_CTX_TASK_ID=loadYtApiOperator
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T04:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-11-28T04:00:00+00:00
[2022-11-29T06:31:55.496+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/opt/airflow/plugins/operators/loadYtApiOperator.py", line 70, in execute
    row.split(",")[11])
IndexError: list index out of range
[2022-11-29T06:31:55.567+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_try_oop, task_id=loadYtApiOperator, execution_date=20221128T040000, start_date=20221129T063154, end_date=20221129T063155
[2022-11-29T06:31:55.665+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 1089 for task loadYtApiOperator (list index out of range; 173)
[2022-11-29T06:31:55.820+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-29T06:31:55.904+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
