[2022-11-28T08:50:00.219+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_youtube_api.transform manual__2022-11-28T08:49:52.733978+00:00 [queued]>
[2022-11-28T08:50:00.241+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: dag_youtube_api.transform manual__2022-11-28T08:49:52.733978+00:00 [queued]>
[2022-11-28T08:50:00.243+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2022-11-28T08:50:00.244+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 2
[2022-11-28T08:50:00.244+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2022-11-28T08:50:00.281+0000] {taskinstance.py:1383} INFO - Executing <Task(PythonOperator): transform> on 2022-11-28 08:49:52.733978+00:00
[2022-11-28T08:50:00.309+0000] {standard_task_runner.py:55} INFO - Started process 1088 to run task
[2022-11-28T08:50:00.322+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'dag_youtube_api', 'transform', 'manual__2022-11-28T08:49:52.733978+00:00', '--job-id', '513', '--raw', '--subdir', 'DAGS_FOLDER/dag_youtube_api.py', '--cfg-path', '/tmp/tmp3xc2vwtq']
[2022-11-28T08:50:00.326+0000] {standard_task_runner.py:83} INFO - Job 513: Subtask transform
[2022-11-28T08:50:00.503+0000] {task_command.py:376} INFO - Running <TaskInstance: dag_youtube_api.transform manual__2022-11-28T08:49:52.733978+00:00 [running]> on host 8af950e53524
[2022-11-28T08:50:00.730+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=dag_youtube_api
AIRFLOW_CTX_TASK_ID=transform
AIRFLOW_CTX_EXECUTION_DATE=2022-11-28T08:49:52.733978+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-11-28T08:49:52.733978+00:00
[2022-11-28T08:50:00.742+0000] {taskinstance.py:1851} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 193, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_youtube_api.py", line 134, in transform
    data = pd.read_csv('/opt/airflow/data/22.28.11_ID_videos.csv')
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/util/_decorators.py", line 311, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 586, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 482, in _read
    parser = TextFileReader(filepath_or_buffer, **kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 811, in __init__
    self._engine = self._make_engine(self.engine)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/readers.py", line 1040, in _make_engine
    return mapping[engine](self.f, **self.options)  # type: ignore[call-arg]
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/c_parser_wrapper.py", line 51, in __init__
    self._open_handles(src, kwds)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/parsers/base_parser.py", line 229, in _open_handles
    errors=kwds.get("encoding_errors", "strict"),
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/io/common.py", line 707, in get_handle
    newline="",
FileNotFoundError: [Errno 2] No such file or directory: '/opt/airflow/data/22.28.11_ID_videos.csv'
[2022-11-28T08:50:00.773+0000] {taskinstance.py:1406} INFO - Marking task as UP_FOR_RETRY. dag_id=dag_youtube_api, task_id=transform, execution_date=20221128T084952, start_date=20221128T085000, end_date=20221128T085000
[2022-11-28T08:50:00.805+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 513 for task transform ([Errno 2] No such file or directory: '/opt/airflow/data/22.28.11_ID_videos.csv'; 1088)
[2022-11-28T08:50:00.898+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2022-11-28T08:50:00.943+0000] {taskinstance.py:2623} INFO - 0 downstream tasks scheduled from follow-on schedule check
